# -*- coding: utf-8 -*-

import datetime

import pytest

from gggdtparser import parse


dt = datetime.datetime
BASE = dt(2026, 9, 18, 15, 4, 5)

EXPECTED = {
    "today": dt(2026, 9, 18),
    "yesterday": dt(2026, 9, 17),
    "tomorrow": dt(2026, 9, 19),
    "day_before_yesterday": dt(2026, 9, 16),
    "day_after_tomorrow": dt(2026, 9, 20),
    "two_hours_later": dt(2026, 9, 18, 17, 0, 0),
    "two_hours_ago": dt(2026, 9, 18, 13, 0, 0),
    "two_minutes_later": dt(2026, 9, 18, 15, 6, 0),
    "two_minutes_ago": dt(2026, 9, 18, 15, 2, 0),
    "next_week": dt(2026, 9, 25),
    "last_week": dt(2026, 9, 11),
    "next_month": dt(2026, 10, 18),
    "last_month": dt(2026, 8, 18),
    "next_year": dt(2027, 1, 1),
    "last_year": dt(2025, 1, 1),
}

LANG_SCENARIOS = {
    "ro": {
        "today": "azi",
        "yesterday": "ieri",
        "tomorrow": "mâine",
        "day_before_yesterday": "alaltăieri",
        "day_after_tomorrow": "poimâine",
        "two_hours_later": "peste 2 ore",
        "two_hours_ago": "acum 2 ore",
        "two_minutes_later": "peste 2 minute",
        "two_minutes_ago": "acum 2 minute",
        "next_week": "săptămâna viitoare",
        "last_week": "săptămâna trecută",
        "next_month": "luna viitoare",
        "last_month": "luna trecută",
        "next_year": "anul viitor",
        "last_year": "anul trecut",
    },
    "bg": {
        "today": "днес",
        "yesterday": "вчера",
        "tomorrow": "утре",
        "day_before_yesterday": "завчера",
        "day_after_tomorrow": "вдругиден",
        "two_hours_later": "след 2 часа",
        "two_hours_ago": "преди 2 часа",
        "two_minutes_later": "след 2 минути",
        "two_minutes_ago": "преди 2 минути",
        "next_week": "следващата седмица",
        "last_week": "миналата седмица",
        "next_month": "следващия месец",
        "last_month": "миналия месец",
        "next_year": "следващата година",
        "last_year": "миналата година",
    },
    "sr": {
        "today": "данас",
        "yesterday": "јуче",
        "tomorrow": "сутра",
        "day_before_yesterday": "прекјуче",
        "day_after_tomorrow": "прекосутра",
        "two_hours_later": "за 2 сата",
        "two_hours_ago": "пре 2 сата",
        "two_minutes_later": "за 2 минута",
        "two_minutes_ago": "пре 2 минута",
        "next_week": "следеће недеље",
        "last_week": "прошле недеље",
        "next_month": "следећег месеца",
        "last_month": "прошлог месеца",
        "next_year": "следеће године",
        "last_year": "прошле године",
    },
    "hr": {
        "today": "danas",
        "yesterday": "jučer",
        "tomorrow": "sutra",
        "day_before_yesterday": "prekjučer",
        "day_after_tomorrow": "prekosutra",
        "two_hours_later": "za 2 sata",
        "two_hours_ago": "prije 2 sata",
        "two_minutes_later": "za 2 minute",
        "two_minutes_ago": "prije 2 minute",
        "next_week": "sljedeći tjedan",
        "last_week": "prošli tjedan",
        "next_month": "sljedeći mjesec",
        "last_month": "prošli mjesec",
        "next_year": "sljedeća godina",
        "last_year": "prošla godina",
    },
    "sk": {
        "today": "dnes",
        "yesterday": "včera",
        "tomorrow": "zajtra",
        "day_before_yesterday": "predvčerom",
        "day_after_tomorrow": "pozajtra",
        "two_hours_later": "o 2 hodiny",
        "two_hours_ago": "pred 2 hodinami",
        "two_minutes_later": "o 2 minúty",
        "two_minutes_ago": "pred 2 minútami",
        "next_week": "budúci týždeň",
        "last_week": "minulý týždeň",
        "next_month": "budúci mesiac",
        "last_month": "minulý mesiac",
        "next_year": "budúci rok",
        "last_year": "minulý rok",
    },
    "sl": {
        "today": "danes",
        "yesterday": "včeraj",
        "tomorrow": "jutri",
        "day_before_yesterday": "predvčerajšnjim",
        "day_after_tomorrow": "pojutrišnjem",
        "two_hours_later": "čez 2 uri",
        "two_hours_ago": "pred 2 urama",
        "two_minutes_later": "čez 2 minuti",
        "two_minutes_ago": "pred 2 minutama",
        "next_week": "naslednji teden",
        "last_week": "prejšnji teden",
        "next_month": "naslednji mesec",
        "last_month": "prejšnji mesec",
        "next_year": "naslednje leto",
        "last_year": "prejšnje leto",
    },
    "lt": {
        "today": "šiandien",
        "yesterday": "vakar",
        "tomorrow": "rytoj",
        "day_before_yesterday": "užvakar",
        "day_after_tomorrow": "poryt",
        "two_hours_later": "po 2 valandų",
        "two_hours_ago": "prieš 2 valandas",
        "two_minutes_later": "po 2 minučių",
        "two_minutes_ago": "prieš 2 minutes",
        "next_week": "kitą savaitę",
        "last_week": "praėjusią savaitę",
        "next_month": "kitą mėnesį",
        "last_month": "praėjusį mėnesį",
        "next_year": "kitais metais",
        "last_year": "praėjusiais metais",
    },
    "lv": {
        "today": "šodien",
        "yesterday": "vakar",
        "tomorrow": "rīt",
        "day_before_yesterday": "aizvakar",
        "day_after_tomorrow": "parīt",
        "two_hours_later": "pēc 2 stundām",
        "two_hours_ago": "pirms 2 stundām",
        "two_minutes_later": "pēc 2 minūtēm",
        "two_minutes_ago": "pirms 2 minūtēm",
        "next_week": "nākamnedēļ",
        "last_week": "pagājušajā nedēļā",
        "next_month": "nākamajā mēnesī",
        "last_month": "pagājušajā mēnesī",
        "next_year": "nākamgad",
        "last_year": "pagājušajā gadā",
    },
    "et": {
        "today": "täna",
        "yesterday": "eile",
        "tomorrow": "homme",
        "day_before_yesterday": "üleeile",
        "day_after_tomorrow": "ülehomme",
        "two_hours_later": "2 tunni pärast",
        "two_hours_ago": "2 tundi tagasi",
        "two_minutes_later": "2 minuti pärast",
        "two_minutes_ago": "2 minutit tagasi",
        "next_week": "järgmisel nädalal",
        "last_week": "eelmisel nädalal",
        "next_month": "järgmisel kuul",
        "last_month": "eelmisel kuul",
        "next_year": "järgmisel aastal",
        "last_year": "eelmisel aastal",
    },
    "ms": {
        "today": "hari ini",
        "yesterday": "semalam",
        "tomorrow": "esok",
        "day_before_yesterday": "kelmarin",
        "day_after_tomorrow": "lusa",
        "two_hours_later": "dalam 2 jam",
        "two_hours_ago": "2 jam lalu",
        "two_minutes_later": "dalam 2 minit",
        "two_minutes_ago": "2 minit lalu",
        "next_week": "minggu depan",
        "last_week": "minggu lepas",
        "next_month": "bulan depan",
        "last_month": "bulan lepas",
        "next_year": "tahun depan",
        "last_year": "tahun lepas",
    },
    "fil": {
        "today": "ngayon",
        "yesterday": "kahapon",
        "tomorrow": "bukas",
        "day_before_yesterday": "noong isang araw",
        "day_after_tomorrow": "sa makalawa",
        "two_hours_later": "sa loob ng 2 oras",
        "two_hours_ago": "2 oras ang nakalipas",
        "two_minutes_later": "sa loob ng 2 minuto",
        "two_minutes_ago": "2 minuto ang nakalipas",
        "next_week": "susunod na linggo",
        "last_week": "nakaraang linggo",
        "next_month": "susunod na buwan",
        "last_month": "nakaraang buwan",
        "next_year": "susunod na taon",
        "last_year": "nakaraang taon",
    },
    "is": {
        "today": "í dag",
        "yesterday": "í gær",
        "tomorrow": "á morgun",
        "day_before_yesterday": "í fyrradag",
        "day_after_tomorrow": "hinn daginn",
        "two_hours_later": "eftir 2 klukkustundir",
        "two_hours_ago": "fyrir 2 klukkustundum",
        "two_minutes_later": "eftir 2 mínútur",
        "two_minutes_ago": "fyrir 2 mínútum",
        "next_week": "næstu viku",
        "last_week": "síðustu viku",
        "next_month": "næsta mánuði",
        "last_month": "síðasta mánuði",
        "next_year": "næsta ári",
        "last_year": "síðasta ári",
    },
    "af": {
        "today": "vandag",
        "yesterday": "gister",
        "tomorrow": "môre",
        "day_before_yesterday": "eergister",
        "day_after_tomorrow": "oormôre",
        "two_hours_later": "oor 2 uur",
        "two_hours_ago": "2 uur gelede",
        "two_minutes_later": "oor 2 minute",
        "two_minutes_ago": "2 minute gelede",
        "next_week": "volgende week",
        "last_week": "verlede week",
        "next_month": "volgende maand",
        "last_month": "verlede maand",
        "next_year": "volgende jaar",
        "last_year": "verlede jaar",
    },
    "ca": {
        "today": "avui",
        "yesterday": "ahir",
        "tomorrow": "demà",
        "day_before_yesterday": "abans-d'ahir",
        "day_after_tomorrow": "demà passat",
        "two_hours_later": "en 2 hores",
        "two_hours_ago": "fa 2 hores",
        "two_minutes_later": "en 2 minuts",
        "two_minutes_ago": "fa 2 minuts",
        "next_week": "la setmana que ve",
        "last_week": "la setmana passada",
        "next_month": "el mes que ve",
        "last_month": "el mes passat",
        "next_year": "l'any que ve",
        "last_year": "l'any passat",
    },
    "mk": {
        "today": "денес",
        "yesterday": "вчера",
        "tomorrow": "утре",
        "day_before_yesterday": "завчера",
        "day_after_tomorrow": "задутре",
        "two_hours_later": "за 2 часа",
        "two_hours_ago": "пред 2 часа",
        "two_minutes_later": "за 2 минути",
        "two_minutes_ago": "пред 2 минути",
        "next_week": "следната недела",
        "last_week": "минатата недела",
        "next_month": "следниот месец",
        "last_month": "минатиот месец",
        "next_year": "следната година",
        "last_year": "минатата година",
    },
    "sq": {
        "today": "sot",
        "yesterday": "dje",
        "tomorrow": "nesër",
        "day_before_yesterday": "pardje",
        "day_after_tomorrow": "pasnesër",
        "two_hours_later": "pas 2 orësh",
        "two_hours_ago": "2 orë më parë",
        "two_minutes_later": "pas 2 minutash",
        "two_minutes_ago": "2 minuta më parë",
        "next_week": "javën e ardhshme",
        "last_week": "javën e kaluar",
        "next_month": "muajin e ardhshëm",
        "last_month": "muajin e kaluar",
        "next_year": "vitin e ardhshëm",
        "last_year": "vitin e kaluar",
    },
    "hy": {
        "today": "այսօր",
        "yesterday": "երեկ",
        "tomorrow": "վաղը",
        "day_before_yesterday": "նախանցյալ օրը",
        "day_after_tomorrow": "վաղը չէ մյուս օրը",
        "two_hours_later": "2 ժամ հետո",
        "two_hours_ago": "2 ժամ առաջ",
        "two_minutes_later": "2 րոպե հետո",
        "two_minutes_ago": "2 րոպե առաջ",
        "next_week": "հաջորդ շաբաթ",
        "last_week": "անցյալ շաբաթ",
        "next_month": "հաջորդ ամիս",
        "last_month": "անցյալ ամիս",
        "next_year": "հաջորդ տարի",
        "last_year": "անցյալ տարի",
    },
    "ka": {
        "today": "დღეს",
        "yesterday": "გუშინ",
        "tomorrow": "ხვალ",
        "day_before_yesterday": "გუშინწინ",
        "day_after_tomorrow": "ზეგ",
        "two_hours_later": "2 საათში",
        "two_hours_ago": "2 საათის წინ",
        "two_minutes_later": "2 წუთში",
        "two_minutes_ago": "2 წუთის წინ",
        "next_week": "მომავალ კვირას",
        "last_week": "გასულ კვირას",
        "next_month": "მომავალ თვეში",
        "last_month": "გასულ თვეში",
        "next_year": "მომავალ წელს",
        "last_year": "გასულ წელს",
    },
    "kk": {
        "today": "бүгін",
        "yesterday": "кеше",
        "tomorrow": "ертең",
        "day_before_yesterday": "алдыңғы күні",
        "day_after_tomorrow": "арғы күні",
        "two_hours_later": "2 сағаттан кейін",
        "two_hours_ago": "2 сағат бұрын",
        "two_minutes_later": "2 минуттан кейін",
        "two_minutes_ago": "2 минут бұрын",
        "next_week": "келесі апта",
        "last_week": "өткен апта",
        "next_month": "келесі ай",
        "last_month": "өткен ай",
        "next_year": "келесі жыл",
        "last_year": "өткен жыл",
    },
    "uz": {
        "today": "bugun",
        "yesterday": "kecha",
        "tomorrow": "ertaga",
        "day_before_yesterday": "oldin kecha",
        "day_after_tomorrow": "indin",
        "two_hours_later": "2 soatdan keyin",
        "two_hours_ago": "2 soat oldin",
        "two_minutes_later": "2 daqiqadan keyin",
        "two_minutes_ago": "2 daqiqa oldin",
        "next_week": "keyingi hafta",
        "last_week": "o'tgan hafta",
        "next_month": "keyingi oy",
        "last_month": "o'tgan oy",
        "next_year": "keyingi yil",
        "last_year": "o'tgan yil",
    },
    "ne": {
        "today": "आज",
        "yesterday": "हिजो",
        "tomorrow": "भोलि",
        "day_before_yesterday": "अस्ति",
        "day_after_tomorrow": "पर्सी",
        "two_hours_later": "२ घण्टा पछि",
        "two_hours_ago": "२ घण्टा अघि",
        "two_minutes_later": "२ मिनेट पछि",
        "two_minutes_ago": "२ मिनेट अघि",
        "next_week": "अर्को हप्ता",
        "last_week": "गत हप्ता",
        "next_month": "अर्को महिना",
        "last_month": "गत महिना",
        "next_year": "अर्को वर्ष",
        "last_year": "गत वर्ष",
    },
}


def _iter_cases():
    for lang, scenarios in sorted(LANG_SCENARIOS.items()):
        for key, text in scenarios.items():
            yield lang, key, text, EXPECTED[key]


@pytest.mark.parametrize(
    "lang,key,text,expected",
    list(_iter_cases()),
)
def test_natural_language_scenarios(lang, key, text, expected):
    assert parse(text, langs=[lang], base_datetime=BASE) == expected


@pytest.mark.parametrize(
    "lang,text,expected",
    [
        ("ro", "5 ianuarie 2022", dt(2022, 1, 5)),
        ("bg", "5 януари 2022", dt(2022, 1, 5)),
        ("sr", "5. јануар 2022.", dt(2022, 1, 5)),
        ("hr", "5 siječanj 2022", dt(2022, 1, 5)),
        ("sk", "5. január 2022", dt(2022, 1, 5)),
        ("sl", "5 januar 2022", dt(2022, 1, 5)),
        ("lt", "5 sausis 2022", dt(2022, 1, 5)),
        ("lv", "5 janvāris 2022", dt(2022, 1, 5)),
        ("et", "5 jaanuar 2022", dt(2022, 1, 5)),
        ("ms", "5 Januari 2022", dt(2022, 1, 5)),
        ("fil", "ika-5 ng Enero 2022", dt(2022, 1, 5)),
        ("is", "5. janúar 2022", dt(2022, 1, 5)),
        ("af", "5 Januarie 2022", dt(2022, 1, 5)),
        ("ca", "5 de gener de 2022", dt(2022, 1, 5)),
        ("mk", "5 јануари 2022", dt(2022, 1, 5)),
        ("sq", "5 janar 2022", dt(2022, 1, 5)),
        ("hy", "5 հունվարի 2022", dt(2022, 1, 5)),
        ("ka", "5 იანვარი 2022", dt(2022, 1, 5)),
        ("kk", "5 қаңтар 2022", dt(2022, 1, 5)),
        ("uz", "5 yanvar 2022", dt(2022, 1, 5)),
        ("ne", "५ जनवरी २०२२", dt(2022, 1, 5)),
    ],
)
def test_month_names(lang, text, expected):
    assert parse(text, langs=[lang]) == expected


@pytest.mark.parametrize(
    "lang,text,expected",
    [
        ("ro-RO", "mâine", EXPECTED["tomorrow"]),
        ("bg-BG", "утре", EXPECTED["tomorrow"]),
        ("sr-RS", "сутра", EXPECTED["tomorrow"]),
        ("hr-HR", "sutra", EXPECTED["tomorrow"]),
        ("sk-SK", "zajtra", EXPECTED["tomorrow"]),
        ("sl-SI", "jutri", EXPECTED["tomorrow"]),
        ("lt-LT", "rytoj", EXPECTED["tomorrow"]),
        ("lv-LV", "rīt", EXPECTED["tomorrow"]),
        ("et-EE", "homme", EXPECTED["tomorrow"]),
        ("ms-MY", "esok", EXPECTED["tomorrow"]),
        ("fil-PH", "bukas", EXPECTED["tomorrow"]),
        ("is-IS", "á morgun", EXPECTED["tomorrow"]),
        ("af-ZA", "môre", EXPECTED["tomorrow"]),
        ("ca-ES", "demà", EXPECTED["tomorrow"]),
        ("mk-MK", "утре", EXPECTED["tomorrow"]),
        ("sq-AL", "nesër", EXPECTED["tomorrow"]),
        ("hy-AM", "վաղը", EXPECTED["tomorrow"]),
        ("ka-GE", "ხვალ", EXPECTED["tomorrow"]),
        ("kk-KZ", "ертең", EXPECTED["tomorrow"]),
        ("uz-UZ", "ertaga", EXPECTED["tomorrow"]),
        ("ne-NP", "भोलि", EXPECTED["tomorrow"]),
    ],
)
def test_bcp47_language_aliases(lang, text, expected):
    assert parse(text, langs=[lang], base_datetime=BASE) == expected
