# -*- coding: utf-8 -*-

import datetime

import pytest

from gggdtparser import parse


dt = datetime.datetime
BASE = dt(2026, 9, 18, 15, 4, 5)

EXPECTED = {
    "today": dt(2026, 9, 18),
    "yesterday": dt(2026, 9, 17),
    "tomorrow": dt(2026, 9, 19),
    "day_before_yesterday": dt(2026, 9, 16),
    "day_after_tomorrow": dt(2026, 9, 20),
    "two_hours_later": dt(2026, 9, 18, 17, 0, 0),
    "two_hours_ago": dt(2026, 9, 18, 13, 0, 0),
    "two_minutes_later": dt(2026, 9, 18, 15, 6, 0),
    "two_minutes_ago": dt(2026, 9, 18, 15, 2, 0),
    "next_week": dt(2026, 9, 25),
    "last_week": dt(2026, 9, 11),
    "next_month": dt(2026, 10, 18),
    "last_month": dt(2026, 8, 18),
    "next_year": dt(2027, 1, 1),
    "last_year": dt(2025, 1, 1),
}

LANG_SCENARIOS = {
    "en": {
        "today": "today",
        "yesterday": "yesterday",
        "tomorrow": "tomorrow",
        "day_before_yesterday": "day before yesterday",
        "day_after_tomorrow": "the day after tomorrow",
        "two_hours_later": "in 2 hours",
        "two_hours_ago": "2 hours ago",
        "next_week": "next week",
        "last_week": "last week",
        "next_month": "next month",
        "last_month": "last month",
        "next_year": "next year",
        "last_year": "last year",
    },
    "de": {
        "today": "heute",
        "yesterday": "gestern",
        "tomorrow": "morgen",
        "two_hours_later": "in 2 Stunden",
        "two_hours_ago": "vor 2 Stunden",
        "next_week": "nächste Woche",
        "last_week": "letzte Woche",
        "next_month": "nächsten Monat",
        "last_month": "letzten Monat",
        "next_year": "nächstes Jahr",
        "last_year": "letztes Jahr",
    },
    "fra": {
        "today": "aujourd'hui",
        "yesterday": "hier",
        "tomorrow": "demain",
        "day_before_yesterday": "avant-hier",
        "day_after_tomorrow": "après-demain",
        "two_hours_later": "dans 2 heures",
        "two_hours_ago": "il y a 2 heures",
        "next_week": "la semaine prochaine",
        "last_week": "semaine dernière",
        "next_month": "mois prochain",
        "last_month": "mois dernier",
        "next_year": "l'année prochaine",
        "last_year": "année dernière",
    },
    "es": {
        "today": "hoy",
        "yesterday": "ayer",
        "tomorrow": "mañana",
        "day_before_yesterday": "anteayer",
        "day_after_tomorrow": "pasado mañana",
        "two_hours_later": "en 2 horas",
        "two_hours_ago": "hace 2 horas",
        "next_week": "la próxima semana",
        "last_week": "la semana pasada",
        "next_month": "el próximo mes",
        "last_month": "el mes pasado",
        "next_year": "el próximo año",
        "last_year": "el año pasado",
    },
    "it": {
        "today": "oggi",
        "yesterday": "ieri",
        "tomorrow": "domani",
        "day_before_yesterday": "l'altro ieri",
        "day_after_tomorrow": "dopodomani",
        "two_hours_later": "tra 2 ore",
        "two_hours_ago": "2 ore fa",
        "next_week": "la prossima settimana",
        "last_week": "la settimana scorsa",
        "next_month": "il prossimo mese",
        "last_month": "il mese scorso",
        "next_year": "l'anno prossimo",
        "last_year": "l'anno scorso",
    },
    "nl": {
        "today": "vandaag",
        "yesterday": "gisteren",
        "tomorrow": "morgen",
        "day_before_yesterday": "eergisteren",
        "day_after_tomorrow": "overmorgen",
        "two_hours_later": "over 2 uur",
        "two_hours_ago": "2 uur geleden",
        "next_week": "volgende week",
        "last_week": "vorige week",
        "next_month": "volgende maand",
        "last_month": "vorige maand",
        "next_year": "volgend jaar",
        "last_year": "vorig jaar",
    },
    "ru": {
        "today": "сегодня",
        "yesterday": "вчера",
        "tomorrow": "завтра",
        "day_before_yesterday": "позавчера",
        "day_after_tomorrow": "послезавтра",
        "two_hours_later": "через 2 часа",
        "two_hours_ago": "2 часа назад",
        "next_week": "следующая неделя",
        "last_week": "прошлая неделя",
        "next_month": "следующий месяц",
        "last_month": "прошлый месяц",
        "next_year": "следующий год",
        "last_year": "прошлый год",
    },
    "tr": {
        "today": "bugün",
        "yesterday": "dün",
        "tomorrow": "yarın",
        "two_hours_later": "2 saat sonra",
        "two_hours_ago": "2 saat önce",
        "next_week": "gelecek hafta",
        "last_week": "geçen hafta",
        "next_month": "gelecek ay",
        "last_month": "geçen ay",
        "next_year": "gelecek yıl",
        "last_year": "geçen yıl",
    },
    "uk": {
        "today": "сьогодні",
        "yesterday": "вчора",
        "tomorrow": "завтра",
        "two_hours_later": "через 2 години",
        "two_hours_ago": "2 години тому",
        "next_week": "наступного тижня",
        "last_week": "минулого тижня",
        "next_month": "наступного місяця",
        "last_month": "минулого місяця",
        "next_year": "наступного року",
        "last_year": "минулого року",
    },
    "pl": {
        "today": "dzisiaj",
        "yesterday": "wczoraj",
        "tomorrow": "jutro",
        "day_before_yesterday": "przedwczoraj",
        "day_after_tomorrow": "pojutrze",
        "two_hours_later": "za 2 godziny",
        "two_hours_ago": "2 godziny temu",
        "next_week": "w przyszłym tygodniu",
        "last_week": "w zeszłym tygodniu",
        "next_month": "w przyszłym miesiącu",
        "last_month": "w zeszłym miesiącu",
        "next_year": "w przyszłym roku",
        "last_year": "w zeszłym roku",
    },
    "sv_se": {
        "today": "idag",
        "yesterday": "igår",
        "tomorrow": "imorgon",
        "day_before_yesterday": "i förrgår",
        "day_after_tomorrow": "i övermorgon",
        "two_hours_later": "om 2 timmar",
        "two_hours_ago": "2 timmar sedan",
        "next_week": "nästa vecka",
        "last_week": "förra veckan",
        "next_month": "nästa månad",
        "last_month": "förra månaden",
        "next_year": "nästa år",
        "last_year": "förra året",
    },
    "swe": {
        "today": "hoje",
        "yesterday": "ontem",
        "tomorrow": "amanhã",
        "two_hours_later": "em 2 horas",
        "two_hours_ago": "há 2 horas",
        "next_week": "próxima semana",
        "last_week": "semana passada",
        "next_month": "próximo mês",
        "last_month": "mês passado",
        "next_year": "próximo ano",
        "last_year": "ano passado",
    },
    "nb": {
        "today": "i dag",
        "yesterday": "i går",
        "tomorrow": "i morgen",
        "day_before_yesterday": "i forgårs",
        "day_after_tomorrow": "i overmorgen",
        "two_hours_later": "om 2 timer",
        "two_hours_ago": "2 timer siden",
        "next_week": "neste uke",
        "last_week": "forrige uke",
        "next_month": "neste måned",
        "last_month": "forrige måned",
        "next_year": "neste år",
        "last_year": "forrige år",
    },
    "da": {
        "today": "i dag",
        "yesterday": "i går",
        "tomorrow": "i morgen",
        "day_before_yesterday": "i forgårs",
        "day_after_tomorrow": "i overmorgen",
        "two_hours_later": "om 2 timer",
        "two_hours_ago": "2 timer siden",
        "next_week": "næste uge",
        "last_week": "sidste uge",
        "next_month": "næste måned",
        "last_month": "sidste måned",
        "next_year": "næste år",
        "last_year": "sidste år",
    },
    "fi": {
        "today": "tänään",
        "yesterday": "eilen",
        "tomorrow": "huomenna",
        "day_before_yesterday": "toissapäivänä",
        "day_after_tomorrow": "ylihuomenna",
        "two_hours_later": "2 tunnin kuluttua",
        "two_hours_ago": "2 tuntia sitten",
        "next_week": "ensi viikolla",
        "last_week": "viime viikolla",
        "next_month": "ensi kuussa",
        "last_month": "viime kuussa",
        "next_year": "ensi vuonna",
        "last_year": "viime vuonna",
    },
    "hu": {
        "today": "ma",
        "yesterday": "tegnap",
        "tomorrow": "holnap",
        "day_before_yesterday": "tegnapelőtt",
        "day_after_tomorrow": "holnapután",
        "two_hours_later": "2 óra múlva",
        "two_hours_ago": "2 órája",
        "next_week": "jövő héten",
        "last_week": "múlt héten",
        "next_month": "jövő hónapban",
        "last_month": "múlt hónapban",
        "next_year": "jövő évben",
        "last_year": "múlt évben",
    },
    "cs": {
        "today": "dnes",
        "yesterday": "včera",
        "tomorrow": "zítra",
        "day_before_yesterday": "předevčírem",
        "day_after_tomorrow": "pozítří",
        "two_hours_later": "za 2 hodiny",
        "two_hours_ago": "2 hodinami zpět",
        "next_week": "příští týden",
        "last_week": "minulý týden",
        "next_month": "příští měsíc",
        "last_month": "minulý měsíc",
        "next_year": "příští rok",
        "last_year": "minulý rok",
    },
    "el": {
        "today": "σήμερα",
        "yesterday": "χθες",
        "tomorrow": "αύριο",
        "day_before_yesterday": "προχθές",
        "day_after_tomorrow": "μεθαύριο",
        "two_hours_later": "σε 2 ώρες",
        "two_hours_ago": "πριν από 2 ώρες",
        "next_week": "επόμενη εβδομάδα",
        "last_week": "προηγούμενη εβδομάδα",
        "next_month": "επόμενο μήνα",
        "last_month": "προηγούμενο μήνα",
        "next_year": "επόμενο έτος",
        "last_year": "προηγούμενο έτος",
    },
    "he": {
        "today": "היום",
        "yesterday": "אתמול",
        "tomorrow": "מחר",
        "day_before_yesterday": "שלשום",
        "day_after_tomorrow": "מחרתיים",
        "two_hours_later": "בעוד 2 שעות",
        "two_hours_ago": "לפני 2 שעות",
        "next_week": "בשבוע הבא",
        "last_week": "בשבוע שעבר",
        "next_month": "בחודש הבא",
        "last_month": "בחודש שעבר",
        "next_year": "בשנה הבאה",
        "last_year": "בשנה שעברה",
    },
    "th": {
        "today": "วันนี้",
        "yesterday": "เมื่อวาน",
        "tomorrow": "พรุ่งนี้",
        "day_before_yesterday": "เมื่อวานซืน",
        "day_after_tomorrow": "มะรืนนี้",
        "two_hours_later": "ในอีก 2 ชั่วโมง",
        "two_hours_ago": "2 ชั่วโมงที่แล้ว",
        "next_week": "สัปดาห์หน้า",
        "last_week": "สัปดาห์ที่แล้ว",
        "next_month": "เดือนหน้า",
        "last_month": "เดือนที่แล้ว",
        "next_year": "ปีหน้า",
        "last_year": "ปีที่แล้ว",
    },
    "ar": {
        "today": "اليوم",
        "yesterday": "أمس",
        "tomorrow": "غدا",
        "day_before_yesterday": "أول أمس",
        "day_after_tomorrow": "بعد غد",
        "two_hours_later": "بعد 2 ساعات",
        "two_hours_ago": "قبل 2 ساعات",
        "next_week": "الأسبوع المقبل",
        "last_week": "الأسبوع الماضي",
        "next_month": "الشهر المقبل",
        "last_month": "الشهر الماضي",
        "next_year": "العام القادم",
        "last_year": "العام الماضي",
    },
    "fa": {
        "today": "امروز",
        "yesterday": "دیروز",
        "tomorrow": "فردا",
        "day_before_yesterday": "پریروز",
        "day_after_tomorrow": "پس‌فردا",
        "two_hours_later": "بعد از ۲ ساعت",
        "two_hours_ago": "۲ ساعت پیش",
        "next_week": "هفته آینده",
        "last_week": "هفته گذشته",
        "next_month": "ماه آینده",
        "last_month": "ماه گذشته",
        "next_year": "سال آینده",
        "last_year": "سال گذشته",
    },
    "bn": {
        "today": "আজ",
        "yesterday": "গতকাল",
        "tomorrow": "আগামীকাল",
        "day_before_yesterday": "গত পরশু",
        "day_after_tomorrow": "আগামী পরশু",
        "two_hours_later": "২ ঘণ্টা পরে",
        "two_hours_ago": "২ ঘণ্টা আগে",
        "next_week": "আগামী সপ্তাহে",
        "last_week": "গত সপ্তাহে",
        "next_month": "আগামী মাসে",
        "last_month": "গত মাসে",
        "next_year": "আগামী বছর",
        "last_year": "গত বছর",
    },
    "gu": {
        "today": "આજે",
        "yesterday": "ગઈકાલે",
        "tomorrow": "આવતીકાલે",
        "two_hours_later": "2 કલાક પછી",
        "two_hours_ago": "2 કલાક પહેલાં",
        "next_week": "આવતા અઠવાડિયે",
        "last_week": "ગયા અઠવાડિયે",
        "next_month": "આવતા મહિને",
        "last_month": "ગયા મહિને",
        "next_year": "આવતા વર્ષે",
        "last_year": "ગયા વર્ષે",
    },
    "pa": {
        "today": "ਅੱਜ",
        "yesterday": "ਬੀਤਿਆ ਕੱਲ੍ਹ",
        "tomorrow": "ਕੱਲ੍ਹ",
        "two_hours_later": "2 ਘੰਟੇ ਬਾਅਦ",
        "two_hours_ago": "2 ਘੰਟੇ ਪਹਿਲਾਂ",
        "next_week": "ਅਗਲੇ ਹਫ਼ਤੇ",
        "last_week": "ਪਿਛਲੇ ਹਫ਼ਤੇ",
        "next_month": "ਅਗਲੇ ਮਹੀਨੇ",
        "last_month": "ਪਿਛਲੇ ਮਹੀਨੇ",
        "next_year": "ਅਗਲੇ ਸਾਲ",
        "last_year": "ਪਿਛਲੇ ਸਾਲ",
    },
    "ta": {
        "today": "இன்று",
        "yesterday": "நேற்று",
        "tomorrow": "நாளை",
        "day_before_yesterday": "நேற்று முந்தைய நாள்",
        "day_after_tomorrow": "நாளை மறுநாள்",
        "two_hours_later": "2 மணி நேரத்தில்",
        "two_hours_ago": "2 மணி நேரத்திற்கு முன்பு",
        "next_week": "அடுத்த வாரம்",
        "last_week": "கடந்த வாரம்",
        "next_month": "அடுத்த மாதம்",
        "last_month": "கடந்த மாதம்",
        "next_year": "அடுத்த ஆண்டு",
        "last_year": "கடந்த ஆண்டு",
    },
    "te": {
        "today": "ఈరోజు",
        "yesterday": "నిన్న",
        "tomorrow": "రేపు",
        "day_before_yesterday": "మొన్న",
        "day_after_tomorrow": "ఎల్లుండి",
        "two_hours_later": "2 గంటల తర్వాత",
        "two_hours_ago": "2 గంటల క్రితం",
        "next_week": "వచ్చే వారం",
        "last_week": "గత వారం",
        "next_month": "వచ్చే నెల",
        "last_month": "గత నెల",
        "next_year": "వచ్చే సంవత్సరం",
        "last_year": "గత సంవత్సరం",
    },
    "hi": {
        "today": "आज",
        "yesterday": "बीता कल",
        "tomorrow": "कल",
        "two_hours_later": "2 घंटे बाद",
        "two_hours_ago": "2 घंटे पहले",
        "next_week": "अगले हफ्ते",
        "last_week": "पिछले हफ्ते",
        "next_month": "अगले महीने",
        "last_month": "पिछले महीने",
        "next_year": "अगले साल",
        "last_year": "पिछले साल",
    },
    "mr": {
        "today": "आज",
        "yesterday": "काल",
        "tomorrow": "उद्या",
        "two_hours_later": "2 तासांनंतर",
        "two_hours_ago": "2 तासांपूर्वी",
        "next_week": "पुढील आठवडा",
        "last_week": "मागील आठवडा",
        "next_month": "पुढील महिना",
        "last_month": "मागील महिना",
        "next_year": "पुढील वर्ष",
        "last_year": "मागील वर्ष",
    },
    "az": {
        "today": "bu gün",
        "yesterday": "dünən",
        "tomorrow": "sabah",
        "two_hours_later": "2 saat sonra",
        "two_hours_ago": "2 saat əvvəl",
        "next_week": "gələn həftə",
        "last_week": "keçən həftə",
        "next_month": "gələn ay",
        "last_month": "keçən ay",
        "next_year": "gələn il",
        "last_year": "keçən il",
    },
    "ky": {
        "today": "бүгүн",
        "yesterday": "кечээ",
        "tomorrow": "эртең",
        "two_hours_later": "2 сааттан кийин",
        "two_hours_ago": "2 саат мурун",
        "next_week": "кийинки жума",
        "last_week": "өткөн жума",
        "next_month": "кийинки ай",
        "last_month": "өткөн ай",
        "next_year": "кийинки жыл",
        "last_year": "өткөн жыл",
    },
    "so": {
        "today": "maanta",
        "yesterday": "shalay",
        "tomorrow": "berri",
        "two_hours_later": "2 saacadood ka dib",
        "two_hours_ago": "2 saacadood ka hor",
        "next_week": "toddobaadka soo socda",
        "last_week": "toddobaadkii hore",
        "next_month": "bisha soo socota",
        "last_month": "bishii hore",
        "next_year": "sanadka soo socda",
        "last_year": "sanadkii hore",
    },
    "sw": {
        "today": "leo",
        "yesterday": "jana",
        "tomorrow": "kesho",
        "two_hours_later": "baada ya saa 2",
        "two_hours_ago": "saa 2 zilizopita",
        "next_week": "wiki ijayo",
        "last_week": "wiki iliyopita",
        "next_month": "mwezi ujao",
        "last_month": "mwezi uliopita",
        "next_year": "mwaka ujao",
        "last_year": "mwaka uliopita",
    },
    "tg": {
        "today": "имрӯз",
        "yesterday": "дирӯз",
        "tomorrow": "фардо",
        "two_hours_later": "пас аз 2 соат",
        "two_hours_ago": "2 соат пеш",
        "next_week": "ҳафтаи оянда",
        "last_week": "ҳафтаи гузашта",
        "next_month": "моҳи оянда",
        "last_month": "моҳи гузашта",
        "next_year": "соли оянда",
        "last_year": "соли гузашта",
    },
    "ur": {
        "today": "آج",
        "yesterday": "گزشتہ کل",
        "tomorrow": "کل",
        "two_hours_later": "2 گھنٹے بعد",
        "two_hours_ago": "2 گھنٹے قبل",
        "next_week": "اگلے ہفتے",
        "last_week": "پچھلے ہفتے",
        "next_month": "اگلے مہینے",
        "last_month": "پچھلے مہینے",
        "next_year": "اگلے سال",
        "last_year": "پچھلے سال",
    },
    "si": {
        "today": "අද",
        "yesterday": "ඊයේ",
        "tomorrow": "හෙට",
        "two_hours_later": "පැය 2 කින්",
        "two_hours_ago": "පැය 2 කට පෙර",
        "next_week": "ලබන සතිය",
        "last_week": "පසුගිය සතිය",
        "next_month": "ලබන මාසය",
        "last_month": "පසුගිය මාසය",
        "next_year": "ලබන වසර",
        "last_year": "පසුගිය වසර",
    },
    "vie": {
        "today": "hôm nay",
        "yesterday": "hôm qua",
        "tomorrow": "ngày mai",
        "day_before_yesterday": "hôm kia",
        "day_after_tomorrow": "ngày kia",
        "two_hours_later": "sau 2 giờ",
        "two_hours_ago": "2 giờ trước",
        "next_week": "tuần sau",
        "last_week": "tuần trước",
        "next_month": "tháng sau",
        "last_month": "tháng trước",
        "next_year": "năm sau",
        "last_year": "năm ngoái",
    },
    "_id": {
        "today": "hari ini",
        "yesterday": "kemarin",
        "tomorrow": "besok",
        "day_before_yesterday": "kemarin dulu",
        "day_after_tomorrow": "lusa",
        "two_hours_later": "dalam 2 jam",
        "two_hours_ago": "2 jam yang lalu",
        "next_week": "minggu depan",
        "last_week": "minggu lalu",
        "next_month": "bulan depan",
        "last_month": "bulan lalu",
        "next_year": "tahun depan",
        "last_year": "tahun lalu",
    },
    "ja": {
        "today": "今日",
        "yesterday": "昨日",
        "tomorrow": "明日",
        "day_before_yesterday": "一昨日",
        "day_after_tomorrow": "明後日",
        "two_hours_later": "2時間後",
        "two_hours_ago": "2時間前",
        "next_week": "来週",
        "last_week": "先週",
        "next_month": "来月",
        "last_month": "先月",
        "next_year": "来年",
        "last_year": "去年",
    },
    "ko": {
        "today": "오늘",
        "yesterday": "어제",
        "tomorrow": "내일",
        "day_before_yesterday": "그저께",
        "day_after_tomorrow": "모레",
        "two_hours_later": "2시간 후",
        "two_hours_ago": "2시간 전",
        "next_week": "다음 주",
        "last_week": "지난 주",
        "next_month": "다음 달",
        "last_month": "지난 달",
        "next_year": "내년",
        "last_year": "작년",
    },
    "zht": {
        "today": "今天",
        "yesterday": "昨天",
        "tomorrow": "明天",
        "two_hours_later": "2小時後",
        "two_hours_ago": "2小時前",
        "next_week": "下週",
        "last_week": "上週",
        "next_month": "下個月",
        "last_month": "上個月",
        "next_year": "明年",
        "last_year": "去年",
    },
}


def _iter_cases():
    for lang, scenarios in sorted(LANG_SCENARIOS.items()):
        for key, text in scenarios.items():
            yield lang, key, text, EXPECTED[key]


@pytest.mark.parametrize(
    "lang,key,text,expected",
    list(_iter_cases()),
)
def test_global_natural_language_scenarios(lang, key, text, expected):
    assert parse(text, langs=[lang], base_datetime=BASE) == expected


@pytest.mark.parametrize(
    "lang,text,expected",
    [
        ("en-US", "tomorrow", EXPECTED["tomorrow"]),
        ("fr-FR", "demain", EXPECTED["tomorrow"]),
        ("de-DE", "morgen", EXPECTED["tomorrow"]),
        ("es-MX", "mañana", EXPECTED["tomorrow"]),
        ("pt-BR", "amanhã", EXPECTED["tomorrow"]),
        ("vi-VN", "ngày mai", EXPECTED["tomorrow"]),
        ("th-TH", "พรุ่งนี้", EXPECTED["tomorrow"]),
        ("zh-TW", "明天", EXPECTED["tomorrow"]),
        ("he-IL", "מחר", EXPECTED["tomorrow"]),
    ],
)
def test_bcp47_language_aliases(lang, text, expected):
    assert parse(text, langs=[lang], base_datetime=BASE) == expected


@pytest.mark.parametrize(
    "lang,text,expected",
    [
        ("az", "5 Yanvar 2022", dt(2022, 1, 5)),
        ("so", "5 Janaayo 2022", dt(2022, 1, 5)),
        ("sw", "5 Januari 2022", dt(2022, 1, 5)),
        ("tg", "5 январ 2022", dt(2022, 1, 5)),
        ("ur", "5 جنوری 2022", dt(2022, 1, 5)),
        ("si", "5 ජනවාරි 2022", dt(2022, 1, 5)),
    ],
)
def test_added_month_names(lang, text, expected):
    assert parse(text, langs=[lang]) == expected
